---
- name: Deploy K3s server
  hosts: queens[0]
  remote_user: overmind
  become: false
  gather_facts: true
  tasks:
    - name: Install K3s server
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" K3S_TOKEN="ACABACABACAB" K3S_KUBECONFIG_MODE="644" K3S_KUBECONFIG_OUTPUT=/home/overmind/.kube/config sh -s - --cluster-init --node-taint node-role.kubernetes.io/control-plane=true:NoSchedule --tls-san {{ ansible_hostname }}.abbie.dev
      args:
        creates: /usr/local/bin/k3s

    - name: Install Helm
      ansible.builtin.shell:
        cmd: curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 /tmp/get_helm.sh && /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

- name: Deploy K3s control plane
  hosts: queens[1:]
  remote_user: overmind
  become: false
  gather_facts: true
  tasks:
    - name: Install K3s server
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" K3S_TOKEN="ACABACABACAB" K3S_KUBECONFIG_MODE="644" K3S_URL="https://{{ hostvars[groups['queens'][0]]['ansible_hostname'] }}.abbie.dev:6443" sh -s - --node-taint node-role.kubernetes.io/control-plane=true:NoSchedule
      args:
        creates: /usr/local/bin/k3s

- name: Deploy K3s worker nodes
  hosts: internal:!queens:!farmers
  remote_user: overmind
  become: false
  gather_facts: true
  tasks:
    - name: Install K3s agent
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" K3S_TOKEN="ACABACABACAB" K3S_URL="https://{{ hostvars[groups['queens'][0]]['ansible_hostname'] }}.abbie.dev:6443" sh -s -
        creates: /usr/local/bin/k3s