---
- name: Deploy K3s server
  hosts: farmers[0]
  remote_user: overmind
  become: false
  gather_facts: true
  tasks:
    - name: Install K3s server
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" K3S_TOKEN="ACABACABACAB" K3S_KUBECONFIG_MODE="644" sh -s - --cluster-init --tls-san {{ ansible_hostname }}.abbie.dev
      args:
        creates: /usr/local/bin/k3s

    - name: Install Helm
      ansible.builtin.shell:
        cmd: curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 /tmp/get_helm.sh && /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

- name: Deploy K3s agents
  hosts: farmers[1:]
  remote_user: overmind
  become: false
  gather_facts: true
  tasks:
    - name: Install K3s agent
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" K3S_TOKEN="ACABACABACAB" K3S_KUBECONFIG_MODE="644" K3S_URL="https://{{ hostvars[groups['farmers'][0]]['ansible_hostname'] }}.abbie.dev:6443" sh -s -
      args:
        creates: /usr/local/bin/k3s