---
- name: Uninstall K3s from all nodes
  hosts: all:!overmind
  remote_user: overmind
  become: true
  gather_facts: true
  tasks:
    - name: Run k3s-uninstall.sh
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      args:
        removes: /usr/local/bin/k3s-uninstall.sh
      failed_when: false

    - name: Run k3s-agent-uninstall.sh  
      ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
      args:
        removes: /usr/local/bin/k3s-agent-uninstall.sh
      failed_when: false